# Generated by Django 5.0.7 on 2024-11-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_usuarios_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.IntegerField(choices=[(1, 'administrador'), (2, 'empleado'), (3, 'superadmin')], default=2),
        ),
    ]
